[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
known_first_party = [ "handlers", "models", "services"]

[tool.ruff]
line-length = 88
target-version = "py310"
lint.extend-select = ["E", "F", "W", "C90"]
exclude = ["__pycache__", "build", "dist", ".venv", "venv"]
